### ISSUE TITLE
How to have percentage always show next to battery icon?

### ISSUE THREAD

**Issue by hamensman** [elParaguayo/qtile-widget-laptopbattery#2]
Not really an issue, but was wondering how to have the percentage next to the icon. Meaning, I want to remove the mouse callback function, and just have the percentage always next to the icon.

I really like how sleek the widget is. The best I've seen!

Probably the only thing this is missing is an `update_interval` interval, whereby users can specify the time it takes for the icon to change.

**Comment by elParaguayo** [comment]
Firstly, thanks for trying the widget.

Secondly, I've put all of my widgets into a separate repo: https://github.com/elParaguayo/qtile-extras/ That's the best place to get the widgets as I won't push any changes to this repo any more.

Thirdly, what you're asking is not an option for the widget at the moment but should be very easy:
``` python
class BatteryWithText(qtile_extras.widget.UPowerWidget):

    def __init__(self, **config):
        qtile_extras.widget.UPowerWidget.__init__(self, **config)
        self.show_text = True
        self.mouse_callbacks = {}
```

Haven't tested it but, I think, it should work!

**Comment by hamensman** [comment]
It works!!
