### ISSUE TITLE
Border at the bottom of the widget

### ISSUE THREAD

**Issue by maplepy** [elParaguayo/qtile-widget-laptopbattery#3]
Hello! 

For some reason the widget has a border at the bottom of it and I am not finding where that comes from. I tried removing every other widget I have but I still have that weird border that is sometimes black so I can't see it but that offsets the text a little too high compared to the other modules.

See here
![image](https://github.com/elParaguayo/qtile-widget-laptopbattery/assets/28269333/8b2e477d-d09a-42bd-a415-fb4ac5aa0f8b)

**Comment by maplepy** [comment]
Note that I did not use any setting and just added `LaptopBatteryWidget()`

**Comment by elParaguayo** [comment]
This repo has not been updated in a while. I've put all of my stuff in the qtile-extras repo instead so can you install that instead. If you still have issues with this then post an issue on that repo please.

**Comment by maplepy** [comment]
Sure ! I will have a look at it, thanks :)
